name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-cargo-check-${{ hashFiles('Cargo.lock') }}
          restore-keys: macos-cargo-check-

      - name: cargo check
        env:
          CARGO_TARGET_DIR: target
          ZIG: zig
        run: cargo check
