name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: macos-cargo-check-${{ hashFiles('Cargo.lock') }}
          restore-keys: macos-cargo-check-

      - name: cargo check
        run: cargo check
